import Head from 'next/head'
import 'swiper/css';
import 'swiper/css/pagination';
import Apartments from "@/components/apartments/Apartments";
import Districts from "@/components/districts/Districts";
import Intro from "@/components/intro/Intro";


export default function Home() {
  return (
    <>
      <Head>
        <title>Главная</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Intro/>
        <Apartments/>
        <Districts/>
      </main>
    </>
  )
}
